### ISSUE TITLE
issue when loading v 2.0.0

### ISSUE THREAD

**Issue by TheCommander64** [MrsDarth/Skirt#6]
`[19:42:50 ERROR]: Error occurred while enabling Skirt v2.0.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseReader(java.io.Reader)'
        at io.github.mrsdarth.skirt.paper.elements.ExprEnchantDisplay$1.<init>(ExprEnchantDisplay.java:40) ~[?:?]
        at io.github.mrsdarth.skirt.paper.elements.ExprEnchantDisplay.<clinit>(ExprEnchantDisplay.java:39) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
        at io.github.mrsdarth.skirt.Skirt.tryLoad(Skirt.java:24) ~[?:?]
        at io.github.mrsdarth.skirt.Skirt.onEnable(Skirt.java:38) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

**Comment by TheCommander64** [comment]
This is the error displayed in console

**Comment by MrsDarth** [comment]
just checking you are on paper 1.16 yes?

**Comment by TheCommander64** [comment]
Yes

**Comment by MrsDarth** [comment]
updated pre release should work now

**Comment by TheCommander64** [comment]
uhh this happens now

**Comment by TheCommander64** [comment]
`[00:33:29 ERROR]: #!#! 
[00:33:29 ERROR]: #!#! [Skript] Severe Error:
[00:33:29 ERROR]: #!#! Could not load map.sk
[00:33:29 ERROR]: #!#! 
[00:33:29 ERROR]: #!#! Something went horribly wrong with Skript.
[00:33:29 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:33:29 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:33:29 ERROR]: #!#! Here is full list of them:
[00:33:29 ERROR]: #!#! skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.26 (https://sk.rayfall.net/) skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect) SkBee v1.13.0-Beta1 (https://github.com/ShaneBeee/SkBee) Skirt v2.0.0 DiSky v3.7.0 (https://disky.itsthesky.info/) SkQuery v4.1.5 Reqn v1.2.3 
[00:33:29 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:33:29 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:33:29 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:33:29 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:33:29 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:33:29 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:33:29 ERROR]: #!#! 
[00:33:29 ERROR]: #!#! Stack trace:
[00:33:29 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for mapcanv
[00:33:29 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:265)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1683)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1650)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1398)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1371)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1337)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:518)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:795)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1414)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1120)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.Section.loadCode(Section.java:99)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:71)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:168)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1134)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:498)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:719)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:533)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:420)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:436)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:532)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1066)
[00:33:29 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
[00:33:29 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:33:29 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[00:33:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134)
[00:33:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[00:33:29 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[00:33:29 ERROR]: #!#! 
[00:33:29 ERROR]: #!#! Version Information:
[00:33:29 ERROR]: #!#!   Skript: 2.6 (latest)
[00:33:29 ERROR]: #!#!     Flavor: skriptlang-github
[00:33:29 ERROR]: #!#!     Date: 17:20:35.482878100
[00:33:29 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[00:33:29 ERROR]: #!#!   Minecraft: 1.16.5
[00:33:29 ERROR]: #!#!   Java: 16.0.2 (OpenJDK 64-Bit Server VM 16.0.2+7-67)
[00:33:29 ERROR]: #!#!   OS: Linux amd64 5.4.124-1-pve
[00:33:29 ERROR]: #!#! 
[00:33:29 ERROR]: #!#! Server platform: Paper
[00:33:29 ERROR]: #!#! 
[00:33:29 ERROR]: #!#! Current node: set all pixels on {_canvas} to (arg-1 parsed as color) (map.sk, line 14)
[00:33:29 ERROR]: #!#! Current item: null
[00:33:29 ERROR]: #!#! 
[00:33:29 ERROR]: #!#! Thread: Server thread
[00:33:29 ERROR]: #!#! 
[00:33:29 ERROR]: #!#! Language: english
[00:33:29 ERROR]: #!#! Link parse mode: DISABLED
[00:33:29 ERROR]: #!#! 
[00:33:29 ERROR]: #!#! End of Error.
[00:33:29 ERROR]: #!#! `
